### ISSUE TITLE
Not working as expected

### ISSUE THREAD

**Issue by JustSage** [mperezi/alfred-git-clone#2]
Hi, trying to run this on BigSur 11.4 ,Alfred4. 
Using zsh, iterm2 and python is located in "/usr/local/opt/python@3.9/libexec/bin/python".
**Alfred is configured to work with iterm2.

It won't find urls from the clipboard, pasting a url in won't trigger the next step.
will appreciate your help :)

**Comment by mikybars** [comment]
Weird. 

I'm currently on BigSur 11.2, Alfred 4.3.4. I will install all the updates tonight and let you know asap.

**Comment by mikybars** [comment]
For what I could see reviewing the workflow you must have Python installed in `/usr/bin/python`. In my machine this is a link to   Python 2.7 provided by the system.

**Comment by JustSage** [comment]
> For what I could see reviewing the workflow you must have Python installed in `/usr/bin/python`. In my machine this is a link to Python 2.7 provided by the system.

True, that is what the system provides but I set the PATH variable to a different path hence running "python" command yields to python3 version.

**Comment by mikybars** [comment]
In such a case I would suggest that you enable debug mode as it is shown here:
![image](https://user-images.githubusercontent.com/43891734/123984580-07f1bd80-d9c5-11eb-8896-4506f946c38e.png)
Then trigger the workflow as usual and get back to me with the ouput of that window.

**Comment by JustSage** [comment]
There you go:


[18:33:13.788] Logging Started...
[18:33:16.267] Clone git repo[Script Filter] Queuing argument '(null)'
[18:33:16.382] Clone git repo[Script Filter] Script with argv '(null)' finished
[18:33:16.383] STDERR: Clone git repo[Script Filter] .
18:33:16 workflow.py:2061 DEBUG    ---------- Clone git repo (1.0.0) ----------
18:33:16 scrape_clipboard.py:35 DEBUG    Git repos from clipboard:
[]
18:33:16 workflow.py:1468 DEBUG    reading settings from /Users/sagebaram/Library/Application Support/Alfred/Workflow Data/com.github.mperezi.alfred.clone/settings.json
18:33:16 workflow.py:2254 DEBUG    set last run version: 1.0.0
18:33:16 workflow.py:2103 DEBUG    ---------- finished in 0.022s ----------
[18:33:16.385] Clone git repo[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      },
      "title": "No git repos found in the clipboard"
    }
  ]
}
[18:33:17.354] Clone git repo[Keyword] Processing complete
[18:33:17.358] Clone git repo[Keyword] Passing output '' to Arg and Vars
[18:33:17.359] Clone git repo[Arg and Vars] Processing complete
[18:33:17.359] Clone git repo[Arg and Vars] Passing output '' to Script Filter
[18:33:17.382] Clone git repo[Script Filter] Queuing argument '(null)'
[18:33:17.544] Clone git repo[Script Filter] Script with argv '(null)' finished
[18:33:17.545] STDERR: Clone git repo[Script Filter] .
18:33:17 workflow.py:2061 DEBUG    ---------- Clone git repo (1.0.0) ----------
18:33:17 scrape_clipboard.py:35 DEBUG    Git repos from clipboard:
[]
18:33:17 workflow.py:1468 DEBUG    reading settings from /Users/sagebaram/Library/Application Support/Alfred/Workflow Data/com.github.mperezi.alfred.clone/settings.json
18:33:17 workflow.py:2254 DEBUG    set last run version: 1.0.0
18:33:17 workflow.py:2103 DEBUG    ---------- finished in 0.021s ----------
[18:33:17.552] Clone git repo[Script Filter] {
  "items": [
    {
      "valid": false,
      "subtitle": "",
      "icon": {
        "path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertCautionIcon.icns"
      },
      "title": "No git repos found in the clipboard"
    }
  ]
}

**Comment by mikybars** [comment]
Do you have clipboard history enabled in Alfred by any chance?

**Comment by JustSage** [comment]
Yes it does, just confirmed. All permissions are granted.

**Comment by mikybars** [comment]
Can you share a screenshot of the clipboard viewer in Alfred?

**Comment by JustSage** [comment]
[
![Screen Shot 2021-07-01 at 1 56 00](https://user-images.githubusercontent.com/50245184/124041559-c0dcea00-da0f-11eb-8224-b042f7c64b56.png)
](url)

Clipboard works

**Comment by mikybars** [comment]
I think I know what's happening. It seems to me that you're getting those URLs by copying them from the address bar in your browser. I can't see the ending of those URLs but I'd bet that they're like https://github.com/mperezi/alfred-git-clone.
For the workflow to trigger correctly they must be either:
* https://github.com/mperezi/alfred-git-clone.git
* git@github.com:mperezi/alfred-git-clone.git

Please note the `.git` at the end. This is how you copy git URLs in the GitHub UI:
![image](https://user-images.githubusercontent.com/43891734/124066717-7bcdad80-da39-11eb-9478-4d2ce31fc38c.png)

**Comment by JustSage** [comment]
Now it makes sense. It works as you explained here. 
The usage section says "Copy the URL" hence you can define it in multiple ways.
I would suggest adding this to the README in the usage section, to be more explicit about it;
or even better, allow pasting the url from the search bar and concatenate .git ... could make the workflow a lot better for HTTPS clones, less mouse usage is the goal with alfred :)!

**Comment by mikybars** [comment]
The URL matching is pretty simple right now. If I dropped the `.git` requirement then it wouldn't be so simple. I'd have to start matching things like github.com, gitlab.com and the like to tell git URLs from regular ones.
